package gozbar

/*
#include <zbar.h>
#cgo LDFLAGS: -lzbar
*/
import "C"

// see zbar_symbol_type_t
const (
	ZBAR_NONE    = C.ZBAR_NONE
	ZBAR_PARTIAL = C.ZBAR_PARTIAL
	ZBAR_EAN8    = C.ZBAR_EAN8
	ZBAR_UPCE    = C.ZBAR_UPCE
	ZBAR_ISBN10  = C.ZBAR_ISBN10
	ZBAR_UPCA    = C.ZBAR_UPCA
	ZBAR_EAN13   = C.ZBAR_EAN13
	ZBAR_ISBN13  = C.ZBAR_ISBN13
	ZBAR_I25     = C.ZBAR_I25
	ZBAR_CODE39  = C.ZBAR_CODE39
	ZBAR_PDF417  = C.ZBAR_PDF417
	ZBAR_QRCODE  = C.ZBAR_QRCODE
	ZBAR_CODE128 = C.ZBAR_CODE128
	ZBAR_SYMBOL  = C.ZBAR_SYMBOL
	ZBAR_ADDON2  = C.ZBAR_ADDON2
	ZBAR_ADDON5  = C.ZBAR_ADDON5
	ZBAR_ADDON   = C.ZBAR_ADDON
)

// see zbar_config_t
const (
	ZBAR_CFG_ENABLE     = C.ZBAR_CFG_ENABLE
	ZBAR_CFG_ADD_CHECK  = C.ZBAR_CFG_ADD_CHECK
	ZBAR_CFG_EMIT_CHECK = C.ZBAR_CFG_EMIT_CHECK
	ZBAR_CFG_ASCII      = C.ZBAR_CFG_ASCII
	ZBAR_CFG_NUM        = C.ZBAR_CFG_NUM
	ZBAR_CFG_MIN_LEN    = C.ZBAR_CFG_MIN_LEN
	ZBAR_CFG_MAX_LEN    = C.ZBAR_CFG_MAX_LEN
	ZBAR_CFG_POSITION   = C.ZBAR_CFG_POSITION
	ZBAR_CFG_X_DENSITY  = C.ZBAR_CFG_X_DENSITY
	ZBAR_CFG_Y_DENSITY  = C.ZBAR_CFG_Y_DENSITY
)
